### PR TITLE
Display tool version below the tool name

### PR DESCRIPTION
**Pull request by ConorDavenport**
Screenshot 2020-04-30 at 16 24 22

https://github.com/nearform/node-clinic-doctor/pull/326

Screenshot 2020-04-30 at 16 22 33

https://github.com/nearform/node-clinic-bubbleprof/pull/364

Screenshot 2020-04-30 at 16 20 24

https://github.com/nearform/node-clinic-flame/pull/114

[Issue FK02](https://trello.com/c/vgIgBXME/843-fk02-visibility-of-system-status)

### CODE REVIEW

**Comment by jasnell** [comment]
Can you drop a screenshot into here to show what it looks like? Easier than doing a full checkout to verify :-)

**Comment by ConorDavenport** [comment]
What do we think about the font size and weight? Is it too hard to understand with a quick glance?

**Comment by goto-bus-stop** [comment]
I think it makes sense. You could add a little `v` in front, that should make it clear to most developers that it's the tool version, I think :)

**Comment by goto-bus-stop** [comment]
Released as :package: `@nearform/clinic-common@3.0.0`

**Pull request merged**
